version: "3.3"

services:
  pg:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    container_name: pg
    volumes:
      - pg:/var/lib/postgresql/data


  api_app:
    build: .
    command: poetry run uvicorn app:app --reload --host 0.0.0.0 --port 8000
    container_name: api_app
    ports:
      - 8001:8000
    volumes:
      - .:/app/
    depends_on:
      - pg
    env_file:
      - app.env

volumes:
  pg:
   driver: local
